server:
    #port: ${EUREKA_PORT:8761}
    port: 8761

eureka:
    environment: DEV
    instance:
        #port: ${EUREKA_PORT:8761}
        port: 8761
        #preferIpAddress: false
        #hostname: ${EUREKA_HOSTNAME:localhost}
        hostname: localhost
        appname: csw_eureka_server
        registerWithEureka: false
        #metadataMap:
        #    instanceId: ${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}
    client:
        registerwithEureka: false
        fetchRegistry: false
<<<<<<< HEAD
    #server:
     #   peer-node-connect-timeout-as: ${eureka.peer.cannection.timeout.ns:3000}
     #   peer-node-read-timeout-ns: ${eureka.peer.read.timeout.ms:3000}
=======
    server:
        peer-node-connect-timeout-as: ${eureka.peer.cannection.timeout.ns:3000}
        peer-node-read-timeout-ns: ${eureka.peer.read.timeout.ms:3000}
>>>>>>> a396791f58d68707bdea9e18b135b8c9cd9f0fcd

management:
    endpoints:
        Web:
            exposure:
                Include: "*"

logging.file: $(LOGS_DIR}/cs_eureka_server.log
logging.file.max-history: 10

spring:
    application:
        name: csw_eureka_server
    zipkin:
        locator:
            discovery:
                enabled: false
    sleuth:
        smapler:
            probability: 1.0
    cloud: 
        discovery:
            client:
                health-indicator:
                    enabled: false
                composite-indicator:
                    enabled: false
