server:
    port: ${EUREKA PORT:8761}

eureka:
    environment: ${SERVICE_ENV_VAR}
    instance:
        port: ${EUREKA_PORT:8761}
        preferIpAddress: false
        hostname: ${EUREKA_HOSTNAME:localhost}
        appname: csw_eureka_server
        registerWithEureka: false
        metadataMap:
            instanceId: ${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:9761}
    client:
        registerwithEureka: false
        fetchRegistry: false
        serviceurl:
            defaultzone: ${EOPS_EUREKA_CLUSTER:http://ah-100158-001.sdi.corp.bankofanerica.com:8761/eureka}
    server:
        peer-node-connect-timeout-as: ${eureka.peer.cannection.timeout.ns:3000}
        peer-node-read-timeout-ns: ${eureka.peer.read.timeout.ms:3000}

management:
    endpoints:
        Web:
            exposure:
                Include: "*"

logging.file: $(LOGS_DIR}/cs_eureka_server.log
logging.file.max-history: 10

spring:
    application:
        name: csw_eureka_server
    zipkin:
        locator:
            discovery:
                enabled: false
    sleuth:
        smapler:
            probability: 1.0
    cloud: 
        discovery:
            client:
                health-indicator:
                    enabled: false
                composite-indicator:
                    enabled: false
